### ISSUE TITLE
Static Ip

### ISSUE THREAD

**Issue by rodrichu** [chylek/FakeWifi#7]
Is it possible on the fake wifi connection? I'm using an android tv box with internet cable and Fake Wifi app.

**Comment by chylek** [comment]
I'm not sure what you're asking for, can you elaborate more on what you want?
This app can't do much with your IP. It works like this: 
1) an app asks the system for a list of available connections (LTE, ethernet, wifi, etc.), 
2) my app intercepts this call and says "I have wifi connection" regardless of the true type of connection. 3) When that app wants to know details, my app presents some fake MAC address and SSID, but copies the IP from the true connection. 

I can't imagine situation when changing that IP to something else would be useful, because it only changes how an app **sees** the IP - the IP itself won't be changed on the actual interface (e.g. ethernet).

**Comment by rodrichu** [comment]
Thank you for the explanation. It’s a great app and understanding how it works is fascinating! I believe what I want to do is simple but way past my poor knowledge. I want to use my tv box as a vpn server. There is an app that supposedly “make it easy”. I need to do some configuration thought (like static ip) on the device I’m trying to set and on router. Or I may have undertood everything wrong to. I will keep trying to learn how this works. Sorry for the trouble.

**Comment by chylek** [comment]
No problem. I can't help you with the VPN, I've never tried to run a server on android. You can try asking on xda-developers.com. Good luck.
